### ISSUE TITLE
Portfolio not loading at the start

### ISSUE THREAD

**Issue by emil0r** [cjohansen/portfolio#29]
I get the following runtime error when trying to load a very barebone portfolio project. From the looks of it, the code tries to add a listener to a document that's not been loaded into the DOM just yet. If I edit any of the files and trigger a reload everything works as expected.

```js
TypeError: Cannot read properties of null (reading 'addEventListener')
    at Function.eval [as cljs$core$IFn$_invoke$arity$variadic] (client.cljs:89:8)
    at Function.eval [as cljs$core$IFn$_invoke$arity$variadic] (ui.cljs:111:4)
    at eval (portfolio.cljs:6:4)
    at eval (<anonymous>)
    at goog.globalEval (main.js:434:11)
    at env.evalLoad (main.js:1405:12)
    at main.js:1612:12
```

**Comment by cjohansen** [comment]
What does your index.html look like? Are you perhaps loading the js bundle in the document head?

**Comment by emil0r** [comment]
Indeed I was. Sorry :)
